// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ReactNode } from "react";
 // or `v1X-appRouter` if you are using Next.js v1X

 export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
   return (
     <html lang="en">
       <body>
       <AppRouterCacheProvider>
           {children}
      </AppRouterCacheProvider>
       </body>
     </html>
   );
 }

